# Generated by Django 4.2.6 on 2024-12-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
